name = "modulo-p/settled-pimt"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'modulo-p/settled-pimt'"

[repository]
user = "modulo-p"
project = "settled-pimt"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.8.0"
source = "github"
